language: python
python:
  - "2.7"
env: ENVLIST=py27-1.5.1,py27-1.4.2,py27-1.3.2
matrix:
  include:
     - python: "3.3"
       env: ENVLIST=py33-1.5.1
install:
  - "pip install . tox --use-mirrors"
script: tox -e $ENVLIST
